### ISSUE TITLE
RFE:  Unauthenticated read-only API access

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#221]
It would be nice if we could access the API for read-only data without having to authenticate.

This is primarily for JS-based frontend UIs that we'd like to have query PDC for release status.

FWIW, it would also be nice for our backend services which *could* authenticate.. but if they're accessing PDC read-only, it would just be simpler if we didn't have to supply them some credentials.

**Comment by sochotnicky** [comment]
I'll just put a note that this should be configurable in any case

**Comment by lubomir** [comment]
I haven't tested this, but I think it would be enough to change the configuration in `REST_FRAMEWORK` section: the value of `DEFAULT_PERMISSION_CLASSES` should change to [`rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly`](http://www.django-rest-framework.org/api-guide/permissions/#djangomodelpermissionsoranonreadonly).

**Comment by ralphbean** [comment]
Cool.  We'll give it a try at some point and report back here.  :)

**Comment by ralphbean** [comment]
So, I [tried it](https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=6b5c9d94dc82b27d3144f33d469ac34eb3bf501a), and it worked:

```python
>>> import requests
>>> response = requests.get('https://pdc.fedorainfracloud.org/rest_api/v1/rpms/', verify=False)
>>> response.json()
{u'count': 0, u'previous': None, u'results': [], u'next': None}
```
