### ISSUE TITLE
No API to create composes

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#227]
I see API documentation here for retrieving a list of composes, but none for creating composes:

https://pdc.fedorainfracloud.org/rest_api/v1/composes/

- Is this expected?
- Am I looking in the wrong place?
- Do we have a version of PDC in place there that is too old?

**Comment by lubomir** [comment]
Your link does not work for me. but this kind of expected. There really is no option to just create a compose.

When you import RPMs (via `compose-rpms`) or images (`compose-image`), the compose will be created if it did not exist before.

There are probably two bugs here: this information should be mentioned in the documentation and there probably should be some option to create compose (most likely by importing `composeinfo.json` file).

**Comment by sochotnicky** [comment]
Hmm, generally creating an empty compose (without rpms or images) is not something I see use case for easily. That's not to say there isn't one. But starting with documenting and linking to compose-rpms and compose-images from the compose resource might be a good start here

**Comment by ralphbean** [comment]
Treat my issue reports with a grain of salt -- it is likely that I'm just very confused about how PDC *should* be used.  I don't have a solid use case for creating an empty compose.

@lubomir is right, I think.  The docs should probably just be updated to mention that composes get created as a side-effect of importing RPMs or images.  That would clear it up.

**Comment by simozhan** [comment]
@ralphbean Docs have been updated in this pull request: 
https://github.com/product-definition-center/product-definition-center/pull/397/
Feel free to reopen this issue if you don't like it.
