### ISSUE TITLE
Add more details to compose-images API docs

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#228]
In the compose-images API docs here:

https://pdc.fedorainfracloud.org/rest_api/v1/compose-images/

It mentions that the POST to create a new compose-image entry should contain information from the composeinfo.json and image-metadata.json files.  Can the docs there be expanded slightly to mention what tools are expected to produce those files?  Is it distill/pungi4?

**Comment by xychu** [comment]
@lubomir, could you help on this?
I believe you or dmach knows :-)

**Comment by sochotnicky** [comment]
@xychu Ralph is correct, the expected input is distill/pungi compose images json (image-manifest.json)

**Comment by lubomir** [comment]
Just for reference, the documentation for the file format is [here](http://release-engineering.github.io/productmd/images-1.0.html). Technically, PDC also understands an older, undocumented version of the format.

You can also create the file using *productmd*. The documentation for that is here: [Images](http://release-engineering.github.io/productmd/images.html). An [example](https://github.com/product-definition-center/product-definition-center/blob/master/pdc/apps/compose/views.py#L820-L850) is available in PDC.

The same applies to RPMs: [file format](http://release-engineering.github.io/productmd/rpms-1.0.html), [generator class](http://release-engineering.github.io/productmd/rpms.html), [example](https://github.com/product-definition-center/product-definition-center/blob/master/pdc/apps/compose/views.py#L660-L691).

**Comment by sochotnicky** [comment]
OK, so maybe linking to the github.io docs for this in respective resources wouldn't be bad...as well as mentioning pungi at least.

**Comment by ralphbean** [comment]
> You can also create the file using productmd.

I see that pungi4 appears to be using productmd under the hood to generate these, so it's hopefully all the same.  :)

**Comment by simozhan** [comment]
@ralphbean Docs have been updated in this pull request: 
https://github.com/product-definition-center/product-definition-center/pull/397/
https://github.com/product-definition-center/product-definition-center/pull/398/
Feel free to reopen this issue if you don't like it.

**Comment by ralphbean** [comment]
Nice!  Thanks @simozhan!  :)
