### ISSUE TITLE
Discussion:  Model ostree repos?

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#232]
Does anyone have any thoughts about how to model ostree repos?

They could probably be modeled with the current tables, but, does pdc has a special way to import them (like it does with composeinfo files from pungi4/distill)?

If not, do we know of anyone talking with the rpm-ostree devs to get it integrated into pungi?  or to get rpm-ostree itself producing similar .json manifest files?

**Comment by sochotnicky** [comment]
I asked about a year ago and there didn't seem to be interest in RCM at the time (or maybe just no time to think about it). I don't know if we'd for example want to keep track of history (previous/next tree) and their contents. Do we just keep track of rpm NVRs or do we have to keep track of all filesystem-level contents?

Generally though - having rpm-ostree producing some kind of manifest/metadata file would be a good first step. I don't think anyone was talking to rpm-ostree devs about this. I could try I guess but I feel like I'd be doing middleman for RCM which might just end up with incorrect results...

**Comment by ralphbean** [comment]
Making a note here that I don't have any direct interest in this feature/bug.  I just noticed that an obvious subset of data was missing and thought that it should be tracked.

**Comment by larry-shi** [comment]
PDC team is restarting development of PDC tool and as one of the activities, we are grooming our backlog. This ticket was evaluated as a requirement which is not part of current PDC roadmap  and will be closed. Please feel free to re-open the ticket if you do not agree with this assessment (providing justification) or reach out to Ren Yang (PDC product owner) or Jan Frieser (PDC project manager) with further requests. We strongly suggest joining our stakeholder review meeting so as you could start participating on PDC roadmap updates.

**Comment by simozhan** [comment]
Help to close this task as larry-shi already explains the reason, but maybe there can be setting some status in github issues which will not be synced to internal.
