### ISSUE TITLE
Query for components by component group?

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#233]
I'm looking for a way to query for all of the components in a component group, but I haven't been able to find it.

- The component groups list returns all of the groups (or just one), but it doesn't include the list of components in each group.  Just the group name.  https://pdc.fedorainfracloud.org/rest_api/v1/component-groups/
- Looking at individual release components doesn't seem to return information about what groups they're a part of:  https://pdc.fedorainfracloud.org/rest_api/v1/release-components/

Related - how do you add/remove release components (or global components) to a group?

**Comment by lubomir** [comment]
Once you create a group, there should be a `components` key for each group, with list of components. There no groups yet, so I can't verify, but it is listed in the documentation at  https://pdc.fedorainfracloud.org/rest_api/v1/component-groups/.

Adding or removing components from/to group is done by updating the group. You need to give it a list of components that should be in the group (no explicit add/remove). Is this too inconvenient for your use case?

Each group is linked to a particular release, and can only include release components from that release. There is no grouping for global components.

**Comment by ralphbean** [comment]
> You need to give it a list of components that should be in the group (no explicit add/remove). Is this too inconvenient for your use case?

No, this should be fine.  :)  Thanks!

**Comment by sochotnicky** [comment]
OK, closing (finally :-))
