### ISSUE TITLE
Document how to configure when behind a reverse proxy

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#270]
We have pdc [now deployed](https://pdc.fedoraproject.org) in our production environment.. and it is set up behind a reverse proxy (with haproxy inbetween).  We had to do some ugly stuff to get mod_auth_mellon to sign its requests correctly (with ServerName and UseCanonicalName).. and somewhere along the way we confused the PDC django app so that the links in its documentation point to the haproxy address, not the X headers that come from the reverseproxy.  See the links on [this page](https://pdc.fedoraproject.org/rest_api/v1/) for an example.

- https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/pdc/frontend/templates/pdc.conf
- https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/pdc/frontend/templates/settings_local.py

Low priority, I think.

**Comment by lubomir** [comment]
I think it might be enough to specify `USE_X_FORWARDED_HOST = True` in the config, but I don't have a place to verify it now.

https://docs.djangoproject.com/en/1.9/ref/settings/#use-x-forwarded-host

**Comment by sochotnicky** [comment]
@ralphbean Any idea of the config option fixes this for Fedora? If yes then we can close this one

**Comment by ralphbean** [comment]
I haven't tried it out yet, but will report back when I do.  Thanks for the ping!

**Comment by ralphbean** [comment]
Confirmed!  It works!

Thanks all!
