### ISSUE TITLE
404 error when trying to import compose

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#290]
This is related to #289 (I think).  When trying to import some composes, we get a 404 error, like this:

```python
[2016-02-29 15:00:23][pdcupdater.handlers.compose   ERROR] Failed to import
    u'http://kojipkgs.fedoraproject.org/compose/branched/Fedora-24-20160228.n.0'
    u'https://pdc.fedoraproject.org/rest_api/v1/compose-images/'
    u'{"detail":"Not found"}'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pdcupdater/handlers/compose.py", line 76, in initialize
    self._import_compose(pdc, compose_id, url)
  File "/usr/lib/python2.7/site-packages/pdcupdater/handlers/compose.py", line 128, in _import_compose
    image_manifest=images,
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python2.7/site-packages/beanbag/namespace.py", line 131, in fn
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/beanbag/url_v1.py", line 102, in call
    return self.make_request(path, verb, kwargs, body)
  File "/usr/lib/python2.7/site-packages/beanbag/url_v1.py", line 155, in make_request
    "Bad response code: %d" % (r.status_code,))
BeanBagException: Bad response code: 404
```

Is there something wrong with the metadata in http://kojipkgs.fedoraproject.org/compose/branched/Fedora-24-20160228.n.0 ? Or is there something wrong with the way PDC is handling it.  Similar to #289, the error message "Not found" is kind of cryptic.  What field or entity is it unable to find?

**Comment by lubomir** [comment]
My guess is that the image type and format do not exist in the database. The image manifest has a couple images with format `raw.xz` and type `raw-xz`. These need to be added in the admin section on the web. There is no API for these, as the idea is that this kind of data should not be changing (much).

I thought the error message should be fixed in current master, but can't find the commit right now.

**Comment by ralphbean** [comment]
Thanks!  That definitely helps.  I got into the admin interface and added a new format and type for this.

**Comment by ralphbean** [comment]
It might be nice to make that error message from the API more descriptive though.  If it could have told me *what* was not found, I (the operator) might have been able to solve it without having to open a ticket.

**Comment by ycheng-aa** [comment]
I am not sure why the error message so ambiguity here. I tested the API with problem somewhat alike. It could give some useful message.
```
(pdc)[ycheng@dhcp-2-61 Downloads]$ pdc_client -s dev -r compose-images -x POST -d "{\"composeinfo\": $(cat /home/ycheng/Downloads/composeinfo.json),\"image_manifest\": $(cat /home/ycheng/Downloads/image-manifest.json), \"release_id\": \"rhel-7.0\"}"
400 {"detail":"Image: Field 'format' has invalid value: aaa"}

```
And QA also verified it in PDC-1341. It could implement that create type or format automatically if PDC found it doesn't exist in PDC. But it maybe not reasonable in business so we didn't do it that way. I am not sure.

**Comment by sochotnicky** [comment]
OK. so this should be fixed already. Closing, but let us know if it reappears
