### ISSUE TITLE
Improve error messages when validating compose on import

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#291]
This RFE stems from the experience I had when encountering #289 and #290.

The error messages indicating that *some* value is not well defined.. but they do not tell you *which* value.  It would be very helpful for debugging if they could tell you more.

**Comment by ralphbean** [comment]
Now that I look more closely at this, I think this might be resolved by #234.

**Comment by sochotnicky** [comment]
I think as you indicate this has been fixed up already. If we find more specific cases where error messages should be improved let us know
