### ISSUE TITLE
Add PDC development activity to Fedora's fedmsg bus

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#292]
It could be nice and it is very easy to set up.

Someone with admin rights on these github repositories simply needs to visit https://apps.fedoraproject.org/github2fedmsg and click to enable the integration there.

**Comment by lubomir** [comment]
I *think* I set it up for this repository. Would you like to have this for the client as well?

Note to self: the organization membership needs to be public, otherwise the repository just does not show up.

**Comment by ralphbean** [comment]
Oop, it may be done and I'm just not paying attention where I should.  Thanks @lubomir!
