### ISSUE TITLE
automatically ingest new image types and format from productmd

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#298]
productmd defines what kinds of image types and image formats there are:

https://github.com/release-engineering/productmd/blob/master/productmd/images.py

pdc also has a db table that lists what kinds of image types and image formats there are.  You have to access the admin panel to add new ones.  I've had to periodically go in and add new ones for our fedora instance.

It would be sweet if I didn't have to do that.  Could pdc (on startup) look at the possible types and formats provided by productmd, and automatically add those to its tables?

**Comment by lubomir** [comment]
This should be fixed by https://github.com/product-definition-center/product-definition-center/commit/e5397b2f8d3a46b46de904b09d6d9f4361687f96.

**Comment by ralphbean** [comment]
Looks good to me.  Thanks!
