### ISSUE TITLE
Put documentation on rtfd.org

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#303]
It looks like you have a nice docs/ directory.

It could be nice if you have it automatically rebuilt and displayed on readthedocs.org

**Comment by lubomir** [comment]
Technically the documentation is available: http://product-definition-center.github.io/product-definition-center/ and rebuilt after each commit as part of Travis CI check.

**Comment by ralphbean** [comment]
Very nice.  Thanks!
