### ISSUE TITLE
Create copr repository for PDC

### ISSUE THREAD

**Issue by sochotnicky** [product-definition-center/product-definition-center#31]
Create something that can be on http://copr.fedoraproject.org/

**Comment by ralphbean** [comment]
:+1: this would be great.  Thanks!

**Comment by ralphbean** [comment]
Has this been created yet?

**Comment by ralphbean** [comment]
Perhaps this?  https://copr.fedoraproject.org/coprs/xchu/pdc/  Not sure of the status.

**Comment by ralphbean** [comment]
Seems it is not ready yet:

```
msg: Error: Package: pdc-server-0.1.0-1.el7.centos.noarch (xchu-pdc)
           Requires: patternfly1
```

**Comment by xychu** [comment]
Hi @ralphbean , thanks for trying.
For that error, `patternfly1` is in another copr repo('patternfly/patternfly1') which is needed to be enabled.
We will add instructions on copr page including installation and deployment.

**Comment by ralphbean** [comment]
This can be closed.
