### ISSUE TITLE
Display all/active/inactive releases, release versions and products

### ISSUE THREAD

**Issue by dmach** [product-definition-center/product-definition-center#319]
There should be a drop-down next to search field that allows user to select between all/active/inactive releases, product versions and products.
Default should be: active

**Comment by bliuredhat** [comment]
@dmach; for the select `all`/`active`/`inactive`; I prefer to set the default value: `all`, not `active`. 
Do you agree?
Please help to add some comments here.

**Comment by bliuredhat** [comment]
This issue have been finished. It have been deployed in dt server, and can check the webUI links as followed .
* https://pdc-dt.host.qe.eng.pek2.redhat.com/release/;
* https://pdc-dt.host.qe.eng.pek2.redhat.com/product/;
* https://pdc-dt.host.qe.eng.pek2.redhat.com/product-version/.
