### ISSUE TITLE
Put messaging plugins under the control of a transaction manager

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#322]
OK, first I'll describe the symptom we see in Fedora:

- pungi4 finishes a compose and publishes a fedmsg message about it.
- our pdc-updater listener notices the message and pulls down the compose info and imports it into PDC
- as the compose is imported, PDC emits an ``org.fedoraproject.prod.pdc.compose`` fedmsg message, saying that it has imported a compose.
- some fedora-qa listener listens for that message, and goes to query PDC for more info about that compose.. but it *fails*  the compose is not there!  When the developers go to check later.. the compose *is* there.  It must be a race condition.

My *theory* is that PDC publishes the message to its notification plugins *before* the DB backend has issued its ``COMMIT;`` statement.

We've noticed that this kind of failure is a pattern across many of our webapps, and we developed (what we think is) a good solution for it in Bodhi2 -- using a transaction manager.  See [the code](https://github.com/fedora-infra/bodhi/blob/develop/bodhi/notifications.py#L45-L71), it's pretty neat!

The gist is that whenever your notification plugins are called, they should *queue* the message instead of sending it immediately.  Only later when the DB transaction is complete, then the notification plugins should be instructed to empty their queues and send all the messages.  If (for some reason) the DB transaction fails, then all the messages in the queues should be dropped (you don't want to publish a message saying "new compose is imported" when the compose was not actually imported due to some late-to-the-party exception near the end of request).

**Comment by lubomir** [comment]
I agree with your theory. However, the way sending messages is implemented now should already prevent this problem. During the request processing, the messages are collected and only send once the request handler is done. We have [a middleware for this](https://github.com/product-definition-center/product-definition-center/blob/master/pdc/apps/utils/middleware.py#L13-L29).

I believe the original motivation was to make sure no messages get sent if something fails in the request, but it should cover this case as well.

Maybe [reordering the middlewares in settings](https://github.com/product-definition-center/product-definition-center/blob/master/pdc/settings.py#L96-L111) could help.

**Comment by ralphbean** [comment]
Very reasonable!  I wonder which middleware layer is responsible committing the db transaction (if any..).  How far up in the list can I move it?  Does it depend on anything above it?  Can I move it to the top?  It looks like it doesn't rely on the ``session`` or anything external like that.. so perhaps I can move it to the top.  I'll try it after the Alpha freeze thaws.

**Comment by lubomir** [comment]
I think it should work even at the top of the list.

Django does not by default tie transactions to HTTP requests. There is an option for it (`ATOMIC_REQUESTS`), but even then the middleware should be outside the transaction.

The import code is marked at function level to be atomic: https://github.com/product-definition-center/product-definition-center/blob/master/pdc/apps/compose/lib.py#L91-L93

**Comment by ralphbean** [comment]
Thanks again @lubomir.

I re-ordered our middleware here:  https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=b7d4fb6f47734c1e58d23d3e65ffdb5c7c5efcd1
