### ISSUE TITLE
Include `subvariant` in images endpoint

### ISSUE THREAD

**Issue by AdamWill** [product-definition-center/product-definition-center#323]
Using the `images` API endpoint - https://pdc.fedoraproject.org/rest_api/v1/images/ - would be easier and more useful if one could query on the recently-added `subvariant` property. That would make it possible to quite easily do, for instance, 'find me the most recent KDE live image for Fedora 24', or whatever.

**Comment by sochotnicky** [comment]
Presumably you mean subvariant support in productmd:
https://github.com/release-engineering/productmd/pull/21

It's good to be specific

**Comment by AdamWill** [comment]
well, except Ralph said in that bug 'this is live now' ~a month ago, and I was testing two weeks ago and could not search on subvariant. Looking at the current final page of Fedora PDC output - https://pdc.fedoraproject.org/rest_api/v1/images/?page=134 - there are still no subvariants there. Is 'live' not meaning what I expect it to?

**Comment by lubomir** [comment]
@sochotnicky I think this request about exposing the field in the `/images/` resource, which is a perfectly valid request. It is currently stored in database, and can be retrieved from `/compose-images/`, but that is probably not enough. It should be a rather simple change – add field to serializer and a new filter.

**Comment by AdamWill** [comment]
In Fedora's PDC, at least, compose-images seems to allow only POST:

https://pdc.fedoraproject.org/rest_api/v1/compose-images/

**Comment by lubomir** [comment]
You can only call get with particular compose id, e.g. https://pdc.fedoraproject.org/rest_api/v1/compose-images/Fedora-24-20160407.n.2/ and it returns the image manifest.

**Comment by sochotnicky** [comment]
FYI this was merged in:
https://github.com/product-definition-center/product-definition-center/pull/357

It is being tested now. I'd maybe wait to close this until after you had a chance to play with it in Fedora stage or prod @AdamWill ?

**Comment by AdamWill** [comment]
yeah, that'd be nice. thanks.

**Comment by sochotnicky** [comment]
I see subvariants in the stage instance at least:
https://pdc.stg.fedoraproject.org/rest_api/v1/compose-images/Fedora-24-20160512.n.0/

Closing

**Comment by sochotnicky** [comment]
Sorry, of course I was supposed to look in images endpoint. It's not yet in stage.
