### ISSUE TITLE
PDC doesn't run with Django 1.10

### ISSUE THREAD

**Issue by dmach** [product-definition-center/product-definition-center#430]
I tried to run PDC from clean git clone and ended up with:
...
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "git/product-definition-center/pdc/apps/bindings/apps.py", line 15, in ready
    self._extend_filters()
  File "git/product-definition-center/pdc/apps/bindings/apps.py", line 26, in _extend_filters
    from . import filters
  File "git/product-definition-center/pdc/apps/bindings/filters.py", line 8, in <module>
    from pdc.apps.common.filters import NullableCharFilter
  File "git/product-definition-center/pdc/apps/common/filters.py", line 41, in <module>
    class MultiValueFilter(django_filters.MethodFilter):
AttributeError: 'module' object has no attribute 'MethodFilter'

**Comment by nirik** [comment]
This looks due to the update of python-django-filter from 0.10.0 to 1.0.x. 

https://django-filter.readthedocs.io/en/master/guide/migration.html#migrating-to-1-0

This has become important for Fedora, as our existing pdc is on Fedora 25, and we are trying to move it to Fedora 27.

**Comment by xiangge** [comment]
Currently we support the django-1.8  and django-filter-0.9, so before you run the project, maybe need to run "pip install -r requirements/devel.txt(production.txt)" first ?

**Comment by ralphbean** [comment]
Ah, thanks @xiangge, but their deployment policies disallow installation from `pypi`.

**Comment by xiangge** [comment]
hmm, maybe manually install the django-1.8 and related packages?

**Comment by hluk** [comment]
Pull request: #529 (upgrade to Django 1.11 - version 1.10 is no longer supported)

**Comment by hluk** [comment]
@ralphbean Do you have time to review #529?

It's bigger change so I want to be sure not to break anything.

In the meantime, I'm using PDC with the upgraded Django for development without any issues.

**Comment by hluk** [comment]
Done! PDC now requires Django 1.11.
