### ISSUE TITLE
Ordering doesn't seem to work

### ISSUE THREAD

**Issue by contyk** [product-definition-center/product-definition-center#439]
I've been using REST queries that contain `ordering` with `pdc.fedoraproject.org` but no matter what I set it to it doesn't seem to work.

Example query: https://pdc.fedoraproject.org/rest_api/v1/unreleasedvariants/?active=True&variant_id=base-runtime&variant_version=f26&fields=variant_release&fields=koji_tag&ordering=-variant_release

The first one I get is `20170404161234`. I would expect `20170616125558`. Ordering by `koji_tag` or any other key I randomly tried doesn't make any difference either, so it's not just about reverse ordering. Perhaps I'm doing something wrong?

**Comment by simozhan** [comment]
@contyk yeah. looks the ordering has some issue for unreleasedvariants.
Actually this new API has not been added in this repo, you can see the pull request is still on pending as our team is focusing on other high priority things. https://github.com/product-definition-center/product-definition-center/pull/431
I guess the fedora PDC instance is against repo fedora-modularity:modularity. If you require it to be fixed soon, maybe you can ask in their backlog. If you are not in a hurry, maybe wait for the review to be finished.

**Comment by hanzz** [comment]
This is actually problem for any PDC endpoint on Fedora. See for example https://pdc.fedoraproject.org/rest_api/v1/releases/?ordering=version

Any ideas how we can debug this more?

**Comment by hluk** [comment]
I cannot reproduce this locally - in both versions 1.2.0 and 1.7.0 ordering works as expected.

This could be issue with in settings file. I tested it with the default configuration (following code is taken from [settings.py](https://github.com/product-definition-center/product-definition-center/blob/e67264e2a18171f3a54fc6f8f709d87c8db67b6d/pdc/settings.py#L98)).

```python
REST_FRAMEWORK = {
    #...
    'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',
                                'pdc.apps.utils.utils.RelatedNestedOrderingFilter'),
    #...
}
```

**Comment by hluk** [comment]
Looks like the ordering filter is missing in [settings_local.py](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/pdc/frontend/templates/settings_local.py?id=2f9504efa89750df32beb0a067344d9174663018#n28).

**Comment by hluk** [comment]
@ralphbean Can you fix this issue by adding `RelatedNestedOrderingFilter` to `settings_local.py` file?

**Comment by hanzz** [comment]
@hluk: I will ask ralph to try that fix on Fedora PDC staging instance, will let you know.

**Comment by ralphbean** [comment]
Yes, can do!  Thanks.

**Comment by ralphbean** [comment]
- https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=7151663037948eb3015010f226786e3b6bb11011
- https://infrastructure.fedoraproject.org/cgit/ansible.git/commit/?id=622c76d18931ac8ea89e61735a58377aae7879c2

**Comment by ralphbean** [comment]
I think this can be closed now.
