### ISSUE TITLE
Please avoid "SLA" in apis and elsewhere

### ISSUE THREAD

**Issue by mattdm** [product-definition-center/product-definition-center#441]
I notice that the [component branches api](https://pdc.stg.fedoraproject.org/rest_api/v1/component-branches/) uses the term `sla` and `slas`. I'd like to avoid this, because as a community distribution, Fedora does not generally have SLAs in the formal sense. (See some related stuff at https://pagure.io/fedora-infrastructure/issue/6140.) Cornell University has a thing called [Service Level Expectations](https://confluence.cornell.edu/display/itsmp/Service+Level+Expectations) which likely fits us better.

What about using `servicelevel` and `servicelevels`? This can represent actual SLAs where that is appropriate, and SLEs where we have that.

**Comment by ralphbean** [comment]
As discussed in IRC, we're going to keep the term in the API but replace it in all public-facing tools (scripts and docs) with `servicelevel`.

This ticket (on the PDC server) can probably be closed.  We'll take up the work elsewhere.

**Comment by larry-shi** [comment]
Closing this issue, see the reason above.
