### ISSUE TITLE
Product versions are set to read-only

### ISSUE THREAD

**Issue by mohanboddu** [product-definition-center/product-definition-center#451]
curl -u : --negotiate -H 'content-type: application/json' -X PATCH -d '{"active":"true"}' https://pdc.fedoraproject.org/rest_api/v1/product-versions/fedora-25/
{"detail":"Can not update read only fields: \"active\"."}

When I tried to change the state of a product version, it gave me the above error. 

Can it be fixed or is there a reason why its set to read-only?

**Comment by simozhan** [comment]
@mohanboddu Actually, this is on purpose. The idea is if the active releases count for this product version is greater than 0, then this product version is active, otherwise, inactive. Does it make sense?

**Comment by mohanboddu** [comment]
@simozhan Thanks for the info, I updated the mapping of releases to product versions.

**Comment by simozhan** [comment]
@mohanboddu Ack. Closed
