### ISSUE TITLE
How do tokens expire?

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#477]
Can you explain how this works?

If a user requests a new token every day.. do those tokens stick around forever?  Are they valid forever?

Do they get automatically expired somehow?  How often?  Can a user request that their token have a shorter expiry?

**Comment by simozhan** [comment]
Unless you refresh the token using auth/token/refresh/, the token will not be expired. If my understanding correct, PDC doesn't provide expiry feature,  maybe we leave it to the user to decide if they want to refresh their token or not. @sochotnicky @lubomir any comments?

**Comment by xiangge** [comment]
Currently I think the refresh token api is something like a manually  expire.

**Comment by hluk** [comment]
It should be possible to extend the [TokenAuthenticationWithChangeSet class](https://github.com/product-definition-center/product-definition-center/blob/cc3238fa7997ee4ca172b34b900b7b42fe03a7b8/pdc/apps/auth/authentication.py#L9), token data model and view for endpoint `/rest_api/v1/auth/token/obtain/` to allow users to optionally choose expiration date.

BTW, you can list valid tokens with following command on server side.

```bash
echo 'select * from authtoken_token;' | django-admin dbshell --settings=pdc.settings
```

There are some very old entries so the tokens seem to be valid forever and the only way to expire old tokens now is to remove old entries from the table (by `created` column).

**Comment by hluk** [comment]
Looks like a security issue. I just picked some old token from 2015 (found in database on dev server) and successfully used it to get "auth/current-user".

@simozhan, @xiangge, Should we mark this as a bug? Not sure if this is just some settings on dev server, but tokens should expire after some time.

**Comment by lubomir** [comment]
Users can request a new token, which will expire the old one (i.e. each user can only have a single token at a time). This is probably not a great solution.

However, if we add an expiration date, should there be something notifying the users that their tokens are about to expire? Should multiple tokens be allowed then?

**Comment by xiangge** [comment]
> Looks like a security issue. I just picked some old token from 2015 (found in database on dev server) and successfully used it to get "auth/current-user".
If you just get the token from db directly, I think this might be not a bug as we design the un-expire token.
Because once the token is generated, it should work.

> but tokens should expire after some time.
We should look at this task from several aspects, if people wrote codes in a daemon instance, maybe they don't want to get the token expire, but someone has security requirements in their env, it needs a expire token, so if we consider to redesign it, we should at list support expire/un-expire token.

>  should there be something notifying the users that their tokens are about to expire? 
Yes, if we do this, I think we should give notice in codes or docs.

> Should multiple tokens be allowed then?
Have no idea, maybe just give one token, then ct can config this as expire/un-expire?

**Comment by simozhan** [comment]
I agree that current solution is feasible and reasonable, although probably not perfect. Maybe we can think about to enhance it in V2, i guess this change will break sth.

**Comment by hluk** [comment]
Token validity s explained in [docs](http://product-definition-center.github.io/product-definition-center/using_api.html#authentication).

If there is need to change the behavior or make it configurable, please open an issue.
